name: Weekly Instagram Story

on:
  schedule:
    - cron: '0 8 * * MON'  # Every Monday at 08:00 UTC
  workflow_dispatch:  # Also allow manual trigger

jobs:
  post_story:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Instagram Story script
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          TOKEN : ${{ secrets.TOKEN }}
          REFRESH_TOKEN : ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID : ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET : ${{ secrets.CLIENT_SECRET }}
          SCOPES : ${{ secrets.SCOPES }}
          TOKEN_URI : ${{ secrets.TOKEN_URI }}
        run: python main.py
